export { default as IconSearch } from "./search.svg";
export { default as IconFacebook } from "./facebook.svg";
export { default as IconYoutube } from "./youtube.svg";
export { default as IconVk } from "./vk.svg";
export { default as IconArrowBottom } from "./arrow-bottom.svg";
export { default as IconArrowRight } from "./arrow-right.svg";
export { default as IconLogo } from "./logo.svg";
export { default as IconBurger } from "./burger.svg";
export { default as IconClose } from "./close.svg";
