on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push

jobs:
  web-deploy-uz:
    name: 🎉 Deploy uz
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20.10.0"

      - name: create env file
        run: |
          touch .env
          echo NEXT_PUBLIC_DOMAIN=${{ secrets.NEXT_PUBLIC_DOMAIN_UZ }} >> .env
          echo DEFAULT_LANG=ru >> .env
          echo NEXT_PUBLIC_WHATSAPP_PHONE=+998933883042 >> .env

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USER_UZ }}
          password: ${{ secrets.PASSWORD }}
          protocol: ${{ secrets.PROTOCOL }}
          local-dir: "./.next/standalone/"

  web-deploy-tr:
    name: 🎉 Deploy tr
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20.10.0"

      - name: create env file
        run: |
          touch .env
          echo NEXT_PUBLIC_DOMAIN=${{ secrets.NEXT_PUBLIC_DOMAIN_TR }} >> .env
          echo DEFAULT_LANG=tr >> .env
          echo NEXT_PUBLIC_WHATSAPP_PHONE=+905494886682 >> .env

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USER_TR }}
          password: ${{ secrets.PASSWORD }}
          protocol: ${{ secrets.PROTOCOL }}
          local-dir: "./.next/standalone/"

  web-deploy-eg:
    name: 🎉 Deploy eg
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20.10.0"

      - name: create env file
        run: |
          touch .env
          echo NEXT_PUBLIC_DOMAIN=${{ secrets.NEXT_PUBLIC_DOMAIN_EG }} >> .env
          echo DEFAULT_LANG=ar >> .env

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USER_EG }}
          password: ${{ secrets.PASSWORD }}
          protocol: ${{ secrets.PROTOCOL }}
          local-dir: "./.next/standalone/"
